### ISSUE TITLE
Camera

### ISSUE THREAD

**Issue by amolreapmind** [AgoraIO/Basic-Video-Broadcasting#51]
Camera is not opening

**Comment by plutoless** [comment]
please provide more info:
1. which demo are you running
2. reproducible steps
3. sdk logs

**Comment by amolreapmind** [comment]
For current demo
Steps to reproduce

1] Open this project in android studio
2] Set appid and token for live project
3] Run project
4] Set channel name

**Comment by amolreapmind** [comment]
[agorasdk.log](https://github.com/AgoraIO/Basic-Video-Broadcasting/files/4001766/agorasdk.log)

**Comment by amolreapmind** [comment]
Hi,
    Can you tell the information in detail about live steaming in 
android.


Thanks,
Amol Magdum

**Comment by plutoless** [comment]
it seems you are setting to change the log file location to 
/storage/emulated/0/io.agora.openlive/log/agora-rtc.log
please collect the log from your specified path

**Comment by tanvidhope** [comment]
@plutoless I'm having the same issue

**Comment by plutoless** [comment]
@tanvidhope  please double check if you have successfully joined channel or not. if you can provide your sdk log it would be easier for us to locate root cause

**Comment by tanvidhope** [comment]
This is my log:

2019-12-29 22:03:55.465 7322-7322/io.agora.openlive W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@1b932f7
2019-12-29 22:03:55.546 7322-7327/io.agora.openlive I/.agora.openliv: Compiler allocated 4MB to compile void android.widget.TextView.<init>(android.content.Context, android.util.AttributeSet, int, int)
2019-12-29 22:03:57.507 7322-7322/io.agora.openlive W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@83aa53a
2019-12-29 22:03:57.525 7322-7322/io.agora.openlive I/AudioManager: In isSpeakerphoneOn(), calling application: io.agora.openlive
2019-12-29 22:03:57.526 7322-7322/io.agora.openlive I/AudioManager: In isSpeakerphoneOn(), calling application: io.agora.openlive
2019-12-29 22:03:57.526 7322-7322/io.agora.openlive I/AudioManager: In isSpeakerphoneOn(), calling application: io.agora.openlive
2019-12-29 22:03:57.526 7322-7322/io.agora.openlive I/AudioManager: In setSpeakerphoneOn(), on: false, calling application: io.agora.openlive
2019-12-29 22:03:57.527 7322-7322/io.agora.openlive I/AudioManager: setSpeakerphoneOn false java.lang.Throwable
        at android.media.AudioManager.setSpeakerphoneOn(AudioManager.java:1358)
        at io.agora.rtc.internal.AudioRoutingController.doSetAudioOutputRouting(AudioRoutingController.java:853)
        at io.agora.rtc.internal.AudioRoutingController.resetAudioRouting(AudioRoutingController.java:1145)
        at io.agora.rtc.internal.AudioRoutingController.access$800(AudioRoutingController.java:29)
        at io.agora.rtc.internal.AudioRoutingController$ControllerStartState.reset(AudioRoutingController.java:476)
        at io.agora.rtc.internal.AudioRoutingController.changeState(AudioRoutingController.java:315)
        at io.agora.rtc.internal.AudioRoutingController.access$700(AudioRoutingController.java:29)
        at io.agora.rtc.internal.AudioRoutingController$ControllerBaseState.setState(AudioRoutingController.java:336)
        at io.agora.rtc.internal.AudioRoutingController.startMonitoring(AudioRoutingController.java:801)
        at io.agora.rtc.internal.RtcEngineImpl.nativeJoinChannel(Native Method)
        at io.agora.rtc.internal.RtcEngineImpl.joinChannel(RtcEngineImpl.java:528)
        at io.agora.openlive.activities.RtcBaseActivity.joinChannel(RtcBaseActivity.java:32)
        at io.agora.openlive.activities.RtcBaseActivity.onCreate(RtcBaseActivity.java:18)
        at io.agora.openlive.activities.LiveActivity.onCreate(LiveActivity.java:35)
        at android.app.Activity.performCreate(Activity.java:7149)
        at android.app.Activity.performCreate(Activity.java:7140)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1288)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3027)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3182)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1916)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-12-29 22:03:57.528 7322-7322/io.agora.openlive I/AudioManager: In setSpeakerphoneOn(), on: true, calling application: io.agora.openlive
2019-12-29 22:03:57.529 7322-7322/io.agora.openlive I/AudioManager: setSpeakerphoneOn true java.lang.Throwable
        at android.media.AudioManager.setSpeakerphoneOn(AudioManager.java:1358)
        at io.agora.rtc.internal.AudioRoutingController.doSetAudioOutputRouting(AudioRoutingController.java:854)
        at io.agora.rtc.internal.AudioRoutingController.resetAudioRouting(AudioRoutingController.java:1145)
        at io.agora.rtc.internal.AudioRoutingController.access$800(AudioRoutingController.java:29)
        at io.agora.rtc.internal.AudioRoutingController$ControllerStartState.reset(AudioRoutingController.java:476)
        at io.agora.rtc.internal.AudioRoutingController.changeState(AudioRoutingController.java:315)
        at io.agora.rtc.internal.AudioRoutingController.access$700(AudioRoutingController.java:29)
        at io.agora.rtc.internal.AudioRoutingController$ControllerBaseState.setState(AudioRoutingController.java:336)
        at io.agora.rtc.internal.AudioRoutingController.startMonitoring(AudioRoutingController.java:801)
        at io.agora.rtc.internal.RtcEngineImpl.nativeJoinChannel(Native Method)
        at io.agora.rtc.internal.RtcEngineImpl.joinChannel(RtcEngineImpl.java:528)
        at io.agora.openlive.activities.RtcBaseActivity.joinChannel(RtcBaseActivity.java:32)
        at io.agora.openlive.activities.RtcBaseActivity.onCreate(RtcBaseActivity.java:18)
        at io.agora.openlive.activities.LiveActivity.onCreate(LiveActivity.java:35)
        at android.app.Activity.performCreate(Activity.java:7149)
        at android.app.Activity.performCreate(Activity.java:7140)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1288)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3027)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3182)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1916)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-12-29 22:03:57.530 7322-7322/io.agora.openlive I/AudioManager: In isSpeakerphoneOn(), calling application: io.agora.openlive
2019-12-29 22:03:57.535 7322-7322/io.agora.openlive E/libc: Access denied finding property "net.dns1"
2019-12-29 22:03:57.535 7322-7322/io.agora.openlive E/libc: Access denied finding property "net.dns2"
2019-12-29 22:03:57.535 7322-7322/io.agora.openlive E/libc: Access denied finding property "net.dns3"
2019-12-29 22:03:57.535 7322-7322/io.agora.openlive E/libc: Access denied finding property "net.dns4"
2019-12-29 22:03:57.539 7322-7393/io.agora.openlive D/*WEBRTCN*: SetRenderAndroidVM
2019-12-29 22:03:57.574 7322-8034/io.agora.openlive W/meiyan: [DEBUG] Surface created!
2019-12-29 22:03:57.589 7322-7322/io.agora.openlive W/Thread-216: type=1400 audit(0.0:288782): avc: denied { node_bind } for scontext=u:r:untrusted_app:s0:c114,c256,c512,c768 tcontext=u:object_r:node:s0 tclass=rawip_socket permissive=0
2019-12-29 22:03:57.609 7322-7393/io.agora.openlive D/*WEBRTCN*: StartRender: thread started: 1367340272
2019-12-29 22:03:57.616 7322-8035/io.agora.openlive I/AGORA_SDK: Surface changed to width 1080 height 1920
2019-12-29 22:04:01.775 7322-7322/io.agora.openlive I/AudioManager: In isBluetoothScoOn(), calling application: io.agora.openlive
2019-12-29 22:04:01.800 7322-7393/io.agora.openlive D/*WEBRTCN*: VideoRenderAndroid dtor
2019-12-29 22:04:01.800 7322-7393/io.agora.openlive D/*WEBRTCN*: StopRender:
2019-12-29 22:04:01.800 7322-8039/io.agora.openlive D/*WEBRTCN*: JavaRenderThreadProcess: Java thread detached
2019-12-29 22:04:01.802 7322-7392/io.agora.openlive D/AudioManager: PPD setMode mode = 0
2019-12-29 22:04:01.802 7322-7392/io.agora.openlive V/AudioManager: Elem: dalvik.system.VMStack.getThreadStackTrace(Native Method)
2019-12-29 22:04:01.802 7322-7392/io.agora.openlive V/AudioManager: Elem: java.lang.Thread.getStackTrace(Thread.java:1538)
2019-12-29 22:04:01.802 7322-7392/io.agora.openlive V/AudioManager: Elem: android.media.AudioManager.setMode(AudioManager.java:1831)
2019-12-29 22:04:01.802 7322-7392/io.agora.openlive V/AudioManager: Elem: io.agora.rtc.internal.RtcEngineImpl.handleEvent(RtcEngineImpl.java:1455)
2019-12-29 22:04:01.802 7322-7392/io.agora.openlive V/AudioManager: Elem: io.agora.rtc.internal.RtcEngineImpl.onEvent(RtcEngineImpl.java:1302)
2019-12-29 22:04:01.978 7322-7393/io.agora.openlive D/*WEBRTCN*: SetRenderAndroidVM

**Comment by plutoless** [comment]
@tanvidhope  this is not our sdk log. please collect it from below path,
/storage/emulated/0/io.agora.openlive/log/agora-rtc.log

**Comment by dangmeng** [comment]
I'm having the same issue 
model: HUAWEI Honor 8x 
OS: android 10 
[agora-rtc.log](https://github.com/AgoraIO/Basic-Video-Broadcasting/files/4453807/agora-rtc.log)

**Comment by plutoless** [comment]
![image](https://user-images.githubusercontent.com/471561/79070240-15ab1c80-7d07-11ea-94c1-62b53b2ce63f.png)
it seems you failed to join the channel. please double check if your token is properly specified.
